/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AlokasiRouteImport } from './routes/alokasi'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as UtangRouteImport } from './routes/utang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlokasiRoute = AlokasiRouteImport.update({
  id: '/alokasi',
  path: '/alokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const UtangRoute = UtangRouteImport.update({
  id: '/utang',
  path: '/utang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alokasi': typeof AlokasiRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/utang': typeof UtangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alokasi': typeof AlokasiRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/utang': typeof UtangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alokasi': typeof AlokasiRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/utang': typeof UtangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/alerts' | '/alokasi' | '/profile' | '/subscription' | '/utang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/alokasi' | '/profile' | '/subscription' | '/utang'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/alokasi'
    | '/profile'
    | '/subscription'
    | '/utang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AlokasiRoute: typeof AlokasiRoute
  ProfileRoute: typeof ProfileRoute
  SubscriptionRoute: typeof SubscriptionRoute
  UtangRoute: typeof UtangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alokasi': {
      id: '/alokasi'
      path: '/alokasi'
      fullPath: '/alokasi'
      preLoaderRoute: typeof AlokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utang': {
      id: '/utang'
      path: '/utang'
      fullPath: '/utang'
      preLoaderRoute: typeof UtangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AlokasiRoute: AlokasiRoute,
  ProfileRoute: ProfileRoute,
  SubscriptionRoute: SubscriptionRoute,
  UtangRoute: UtangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
